export const recipes = [
    {
        title: "Chocolate Chip Cookies",
        prepTime: "15 minutes",
        cookTime: "10 minutes",
        servings: "24 cookies",
        ingredients: [
            "1 cup unsalted butter, melted",
            "1 cup white sugar",
            "1 cup packed brown sugar",
            "2 teaspoons vanilla extract",
            "2 large eggs",
            "3 cups all-purpose flour",
            "1 teaspoon baking soda",
            "1/2 teaspoon baking powder",
            "1 teaspoon salt",
            "2 cups semisweet chocolate chips",
        ],
        instructions: [
            "Preheat the oven to 350°F (175°C).",
            "Cream together the melted butter, white sugar, and brown sugar until well blended.",
            "Beat in the vanilla, eggs, and egg yolk until light and creamy.",
            "Mix in the sifted ingredients until just blended. Stir in the chocolate chips by hand using a wooden spoon.",
            "Drop cookie dough 1/4 cup at a time onto prepared cookie sheets. Cookies should be about 3 inches apart.",
            "Bake for 15 to 17 minutes in the preheated oven, or until the edges are lightly toasted.",
            "Cool on baking sheets for a few minutes before transferring to wire racks to cool completely.",
        ],
    },
    {
        title: "Spaghetti Carbonara",
        prepTime: "10 minutes",
        cookTime: "20 minutes",
        servings: "4 servings",
        ingredients: [
            "200g pancetta",
            "50g pecorino cheese",
            "50g parmesan",
            "3 large eggs",
            "350g spaghetti",
            "2 plump garlic cloves, peeled and left whole",
            "50g unsalted butter",
            "Sea salt and freshly ground black pepper",
        ],
        instructions: [
            "Put a large saucepan of water on to boil.",
            "Finely chop the pancetta, having first removed any rind.",
            "Finely grate both cheeses and mix them together.",
            "Beat the eggs in a medium bowl, season with a little freshly grated black pepper and set everything aside.",
            "Add 1 tsp salt to the boiling water, add the spaghetti and when the water comes back to the boil, cook at a constant simmer.",
            "Squash 2 peeled plump garlic cloves with the blade of a knife, just to bruise it.",
            "Melt 50g unsalted butter in a large frying pan and, as soon as the butter has melted, tip in the pancetta and garlic.",
            "Leave to cook on a medium heat for about 5 minutes, stirring often, until the pancetta is golden and crisp.",
            "Keep the heat under the pancetta on low. When the pasta is ready, lift it from the water with a pasta fork or tongs and put it in the frying pan with the pancetta.",
            "Take the pan of spaghetti and pancetta off the heat.",
            "Quickly pour in the eggs and cheese. Using the tongs or a long fork, lift up the spaghetti so it mixes easily with the egg mixture.",
        ],
    },
    {
        title: "Classic Margherita Pizza",
        prepTime: "20 minutes",
        cookTime: "15 minutes",
        servings: "2 pizzas",
        ingredients: [
            "1 1/2 cups warm water",
            "2 teaspoons sugar",
            "2 1/4 teaspoons active dry yeast",
            "3 1/2 cups all-purpose flour",
            "2 tablespoons olive oil",
            "1 teaspoon salt",
            "1/2 cup tomato sauce",
            "200g fresh mozzarella, sliced",
            "1/4 cup fresh basil leaves",
            "2 tablespoons olive oil",
            "Salt and pepper to taste",
        ],
        instructions: [
            "In a small bowl, dissolve sugar in warm water. Sprinkle yeast over the top, and let stand for about 10 minutes, until foamy.",
            "In a large bowl, combine flour, olive oil, and salt. Pour in the yeast mixture, and mix until the dough comes together.",
            "Knead the dough on a lightly floured surface until smooth and elastic.",
            "Place the dough in a lightly oiled bowl, cover with plastic wrap, and let rise in a warm place for about 1 hour, or until doubled in volume.",
            "Preheat oven to 475°F (245°C).",
            "Punch down the risen dough, and divide into 2 pieces.",
            "Roll out each piece to form a pizza base. Place on a lightly floured pizza peel or baking sheet.",
            "Spread tomato sauce over the bases, then top with slices of mozzarella and fresh basil leaves.",
            "Drizzle with olive oil, and season with salt and pepper.",
            "Bake in the preheated oven for 10-15 minutes, or until the crust is golden and the cheese is bubbly.",
        ],
    },
];
